ri_admin_index:
    pattern:  /index
    defaults: { _controller: RIAdminBundle:Admin:index }

ri_admin_ajouter_stage:
    pattern:  /ajout/stage
    defaults: { _controller: RIAdminBundle:Admin:ajoutStage}

ri_admin_ajout_partenaire:
    pattern:  /ajout/partenaire
    defaults: { _controller: RIAdminBundle:Admin:ajoutPartenaire}
    requirements:
        _scheme:  htpps  

ri_admin_ajout_contact:
    pattern:  /ajout/contact
    defaults: { _controller: RIAdminBundle:Admin:ajoutContact}
    requirements:
        
ri_admin_ajout_statut_partenaire:
    pattern:  /admin/ajout/statutpartenaire
    defaults: { _controller: RIAdminBundle:Admin:ajoutStatut}
    requirements:
        _scheme:  htpps

    pattern:  /ajoutstatutpartenaire
    defaults: { _controller: RIAdminBundle:Admin:ajoutStatutPartenaire}

