ri_homepage:
    pattern: /hello/{name}
    defaults: { _controller: RIAdminBundle:Admin:indexTest }
   

ri_admin_index:
    pattern:  /index
    defaults: { _controller: RIAdminBundle:Admin:index }
   
      

ri_admin_ajouter_stage:
    pattern:  /ajout/stage
    defaults: { _controller: RIAdminBundle:Admin:ajoutStage}
   
ri_admin_ajout_partenaire:
    pattern:  /ajout/partenaire
    defaults: { _controller: RIAdminBundle:Admin:ajoutPartenaire}
   
ri_admin_ajout_contact:
    pattern:  /ajout/contact
    defaults: { _controller: RIAdminBundle:Admin:ajoutContact}
    requirements:
        
ri_admin_ajout_statut_partenaire:
    pattern:  /ajoutstatutpartenaire
    defaults: { _controller: RIAdminBundle:Admin:ajoutStatutPartenaire}
    