risite_secAcc:
    pattern:  /secretaire
    defaults: { _controller: RISecBundle:Sec:index }

risite_documentSec:
    pattern: /documentSec
    defaults: { _controller: RISecBundle:Sec:voirDocumentSec }

risite_inscEtu:
    pattern: /inscEtu
    defaults: { _controller: RISecBundle:Sec:voirInscEtu }