<?php

namespace RI\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PartenaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartenaireRepository extends EntityRepository
{
    public function getContact($id){
        $contact=$this->createQueryBuilder('a')
                ->select('c.cont_nom, c.cont_prenom')->from('RISiteBundle:Contact', 'c')
                ->where('c.partenaire = :id')->setParameter('id', $id);
        return $contact->getQuery()->getResult();
    }
}
