risite_profil:
    pattern: /profil/{id}
    defaults: { _controller: RIEtuBundle:Etu:voirProfil }

risite_partenaire:
    pattern: /partenaire/{id}
    defaults: { _controller: RIEtuBundle:Etu:voirPartenaire }

risite_document:
    pattern: /document/{id}
    defaults: { _controller: RIEtuBundle:Etu:voirDocument }