risite_profil:
    pattern: /profil
    defaults: { _controller: RIEtuBundle:Etu:voirProfil }

risite_partenaire:
    pattern: /partenaire
    defaults: { _controller: RIEtuBundle:Etu:voirPartenaire }

risite_document:
    pattern: /document
    defaults: { _controller: RIEtuBundle:Etu:voirDocument }