risite_accueil:
   pattern: /accueil
   defaults: { _controller: RISiteBundle:Site:index }

risite_etudiant:
    pattern: /etudiant/{id}
    defaults: { _controller: RISiteBundle:Site:voirEtudiant }

risite_partenaire:
    pattern: /partenaire/{id}
    defaults: { _controller: RISiteBundle:Site:voirPartenaire }
    
    
risite_contact:
    pattern: /contact/{id}
    defaults: { _controller: RISiteBundle:Site:voirContact }

risite_profil:
    pattern: /profil/{id}
    defaults: { _controller: RISiteBundle:Site:voirProfil }

risite_partenaire:
    pattern: /partenaire
    defaults: { _controller: RISiteBundle:Site:voirPartenaire }

risite_document:
    pattern: /document/{id}
    defaults: { _controller: RISiteBundle:Site:voirDocument }

risite_test:
    pattern: /test
    defaults: { _controller: RISiteBundle:Site:test}