risite_accueil:
   pattern: /
   defaults: { _controller: RISiteBundle:Site:index }

risite_profil:
    pattern: /profil/{id}
    defaults: { _controller: RISiteBundle:Site:voirProfil }

risite_partenaires:
    pattern: /partenaires
    defaults: { _controller: RISiteBundle:Site:voirPartenaires }

risite_partenaire_info:
    pattern: /partenaire/{id}
    defaults: { _controller: RISiteBundle:Site:voirInfoPartenaire }

risite_contact_info:
    pattern: /contact/{id}
    defaults: { _controller: RISiteBundle:Site:voirInfoContact }

risite_stages:
    pattern: /stages
    defaults: { _controller: RISiteBundle:Site:voirStages }

risite_stage_info:
    pattern: /stage/{idStage}
    defaults: { _controller: RISiteBundle:Site:voirInfoStage }

risite_document:
    pattern: /document
    defaults: { _controller: RISiteBundle:Site:voirDocument }

risite_documentSec:
    pattern: /documentSec
    defaults: { _controller: RISiteBundle:Site:voirDocumentSec }

risite_inscEtu:
    pattern: /inscEtu
    defaults: { _controller: RISiteBundle:Site:voirInscEtu }

risite_test:
    pattern: /test
    defaults: { _controller: RISiteBundle:Site:test}