risite_accueil:
   pattern: /
   defaults: { _controller: RISiteBundle:Site:index }

risite_profil:
    pattern: /profil
    defaults: { _controller: RISiteBundle:Site:voirProfil }

risite_profil2:
    pattern: /profil/{id}
    defaults: { _controller: RISiteBundle:Site:voirProfil2 }

risite_partenaires:
    pattern: /partenaires
    defaults: { _controller: RISiteBundle:Site:voirPartenaires }

risite_etudiants:
    pattern: /etudiants
    defaults: { _controller: RISiteBundle:Site:voirEtudiants }

risite_partenaire_info:
    pattern: /partenaire/{id}
    defaults: { _controller: RISiteBundle:Site:voirInfoPartenaire }

risite_contact_info:
    pattern: /contact/{id}
    defaults: { _controller: RISiteBundle:Site:voirInfoContact }

risite_stages:
    pattern: /stages
    defaults: { _controller: RISiteBundle:Site:voirStages }

risite_stage_info:
    pattern: /stage/{idStage}
    defaults: { _controller: RISiteBundle:Site:voirInfoStage }

risite_document:
    pattern: /document
    defaults: { _controller: RISiteBundle:Doc:voirDocument }

risite_document_suppr:
    pattern: /document/supprimer/{id}
    defaults: { _controller: RISiteBundle:Doc:supprimerDocument }

risite_document_suppr_admin:
    pattern: /document/supprimer-admin/{idUser}-document{id}
    defaults: { _controller: RISiteBundle:Doc:supprimerDocument2 }

risite_document_envoi:
    pattern: /document/envoyer/{user}
    defaults: { _controller: RISiteBundle:Doc:envoiDocument }

risite_document_dl:
    pattern: /document/telecharger/{id}
    defaults: { _controller: RISiteBundle:Doc:telechargerDocument }

risite_document_dl_public:
    pattern: /document/telecharger-public/{id}
    defaults: { _controller: RISiteBundle:Doc:telechargerDocument2 }

risite_document_dl_admin:
    pattern: /document/telecharger-admin/{id}
    defaults: { _controller: RISiteBundle:Doc:telechargerDocument3 }

risite_document_user:
    pattern: /document/recherche/{user}
    defaults: { _controller: RISiteBundle:Doc:voirDocUsers }

risite_inscrireetudiant:
    pattern: /inscrire-etudiant
    defaults: { _controller: RISiteBundle:Secretaire:inscrireEtudiant }
   
risite_demandesuppression:
    pattern: /suppression-compte
    defaults: { _controller: RISiteBundle:Site:demandeSuppression }

risite_supprimeretudiant:
    pattern: /suppression/{id}
    defaults: { _controller: RISiteBundle:Secretaire:suppressionCompte }
    
risite_liste_demandes:
    pattern: /demandes-etudiants
    defaults: { _controller: RISiteBundle:Secretaire:voirUsers }