risite_accueil:
   pattern: /
   defaults: { _controller: RISiteBundle:Site:index }

risite_profil:
    pattern: /profil
    defaults: { _controller: RISiteBundle:Site:voirProfil }

risite_partenaires:
    pattern: /partenaires
    defaults: { _controller: RISiteBundle:Site:voirPartenaires }

risite_document:
    pattern: /document
    defaults: { _controller: RISiteBundle:Site:voirDocument }

risite_documentSec:
    pattern: /documentSec
    defaults: { _controller: RISiteBundle:Site:voirDocumentSec }

risite_inscEtu:
    pattern: /inscEtu
    defaults: { _controller: RISiteBundle:Site:voirInscEtu }

risite_gestionPart:
    pattern: /gestionPart
    defaults: { _controller: RISiteBundle:Site:voirGestionPart }

risite_stageEtu:
    pattern: /stageEtu
    defaults: { _controller: RISiteBundle:Site:voirStageEtu }

risite_test:
    pattern: /test
    defaults: { _controller: RISiteBundle:Site:test}