risite_accueil:
   pattern: /
   defaults: { _controller: RISiteBundle:Site:index }

risite_profil:
    pattern: /profil
    defaults: { _controller: RISiteBundle:Site:voirProfil }

risite_partenaires:
    pattern: /partenaires
    defaults: { _controller: RISiteBundle:Site:voirPartenaires }

risite_partenaire_info:
    pattern: /partenaire/{id}
    defaults: { _controller: RISiteBundle:Site:voirInfoPartenaire }

risite_contact_info:
    pattern: /contact/{id}
    defaults: { _controller: RISiteBundle:Site:voirInfoContact }

risite_stages:
    pattern: /stages
    defaults: { _controller: RISiteBundle:Site:voirStages }

risite_stage_info:
    pattern: /stage/{idStage}
    defaults: { _controller: RISiteBundle:Site:voirInfoStage }

risite_document:
    pattern: /document
    defaults: { _controller: RISiteBundle:Doc:voirDocument }

risite_document_suppr:
    pattern: /document/supprimer/{id}
    defaults: { _controller: RISiteBundle:Doc:supprimerDocument }

risite_document_dl:
    pattern: /document/telecharger/{id}
    defaults: { _controller: RISiteBundle:Doc:telechargerDocument }

risite_inscrireetudiant:
    pattern: /inscrire-etudiant
    defaults: { _controller: RISiteBundle:Site:inscrireEtudiant }

risite_test:
    pattern: /test
    defaults: { _controller: RISiteBundle:Site:test}
    
risite_demandesuppression:
    pattern: /suppression-compte
    defaults: { _controller: RISiteBundle:Site:demandeSuppression }

risite_supprimeretudiant:
    pattern: /suppression/{id}
    defaults: { _controller: RISiteBundle:Secretaire:suppressionCompte }
    
risite_profiluser:
    pattern: /demandes-etudiants
    defaults: { _controller: RISiteBundle:Secretaire:voirUsers }