risite_partAcc:
    pattern:  /partAcc
    defaults: { _controller: RIPartBundle:Part:index }

risite_stagiaire:
    pattern: /stagiaire
    defaults: { _controller: RIPartBundle:Part:voirStagiaire }

risite_documentPart:
    pattern: /documents
    defaults: { _controller: RIPartBundle:Part:voirDocPart }